language: node_js
node_js:
    - "8"

jobs:
    include:
        - stage: unit tests
        script:
            - yarn lint
            - yarn test:ci
        - stage: smoke tests
        script:
            - echo one

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8a985c339fa9ce08ee46
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
